Bug - 1637596
mozilla/treeherder pull request #6738
Opened 2020-08-27 03:45 UTC by Tintinator

React-virtualized's `List` component is not compatible with reactstrap's `Input` component because there exists a `div`. As a result, we can't use `Input`'s `multiple` attribute and the jobs are no longer selectable. I could try and create my own select functionality, but wanted to see if there's a cleaner way of going about this. 

To recreate, navigate to "Add New Jobs (Search)" and the message should appear in console.

2020-08-27 16:47 UTC, Tintinator commented
@camd

2020-08-28 23:39 UTC, camd commented
I ran out of time to review this today.  I will review it on Monday.

2020-09-01 23:56 UTC, camd commented
Sorry, I again ran out of time.  I will have to review this on Wednesday.

2020-09-02 19:50 UTC, camd commented
@Tintinator : The solution to this issue is NOT to have the `List` wrapped in a `select`.  This will take some research to track down a solution to handling the clicks within the list to switch which list they're in.  It just won't be with an outer `select`.  You may experiment with using a clicke-able item in `renderJob` rather than a `div`.  That's where I would start.  :)

2020-09-02 19:52 UTC, camd requested changes
As stated earlier, remove the outer `select` and manage clicking within the `renderJob`.  At least try that as an option.

2021-02-04 21:54 UTC, sarah-clements commented
If you're able to pick this issue up again, please reopen a pr and comment in the bugzilla bug. Thanks!

2021-02-04 21:54 UTC, closed without merging