Bug 1611158 - Subtest view - include the platform in the subtest name
mozilla/treeherder pull request #6740
Opened 2020-08-27 14:50 UTC by esanuandra

2020-08-28 08:39 UTC, ionutgoldan reviewed
This is looking good!

What's left here is the test coverage. Could you look for a way to provide it, so this functionality won't break in the future?

2020-08-31 06:27 UTC, ionutgoldan requested changes

2020-08-31 06:27 UTC, ionutgoldan commented on tests/ui/perfherder/compare-view/compare_page_title_test.jsx
> +  pageTitle = await waitFor(() => getByTestId('compare-page-title'));
Don't grab the title by `id`, as that's coding against implementation. Query by the title's text directly.
That way, if we'll changed the underlying HTML structure, the tests won't break.

2020-08-31 06:27 UTC, ionutgoldan commented on tests/ui/perfherder/compare-view/compare_page_title_test.jsx
> +  expect(pageTitle.textContent).toBe('Perfherder Compare Revisions');
I don't see the point of testing this main title. This logic isn't specific to `ComparePageTitle`, but to the client code.

2020-08-31 06:27 UTC, ionutgoldan commented on tests/ui/perfherder/compare-view/compare_page_title_test.jsx
> +      defaultPageTitle={defaultPageTitle}
We need another test for the logic used for `defaultPageTitle`.

2020-09-16 07:31 UTC, ionutgoldan commented on tests/ui/perfherder/compare-view/compare_page_title_test.jsx
> +  const pageTitle = await waitFor(() => getByText(`${title}subtest summary`));
Typo, as we forgot space?

2020-09-16 07:32 UTC, ionutgoldan commented on tests/ui/perfherder/compare-view/compare_page_title_test.jsx
> +  expect(pageTitle.textContent).toBe(`${title} subtest summary`);
I think we could just check the existence of an element with this title.

2020-09-16 08:20 UTC, ionutgoldan approved these changes

2020-09-17 00:42 UTC, sarah-clements commented on ui/shared/ComparePageTitle.jsx
> +      // eslint-disable-next-line react/no-did-update-set-state
Rather than disabling this rule, can you find a workaround so you don't need to?

2020-09-18 21:23 UTC, sarah-clements approved these changes

2020-09-22 07:10 UTC, merged