Created migration to remove deprecated columns from performance_datum
mozilla/treeherder pull request #6804
Opened 2020-10-14 08:35 UTC by beatrice-acasandrei

2020-10-15 10:34 UTC, ionutgoldan requested changes
We forgot to delete [this comment](https://github.com/mozilla/treeherder/blob/a935ecac10bf4253924acc08022884bcc57c1102/tests/conftest.py#L744) as well.

2020-10-15 10:36 UTC, ionutgoldan commented
[This line](https://github.com/mozilla/treeherder/blob/368c112266f4f276251a4886a5337fcb17b3a1e9/treeherder/perf/management/commands/test_analyze_perf.py#L107) should be updated as well.

2020-10-27 10:24 UTC, ionutgoldan approved these changes
Looking good now!

2020-11-02 17:49 UTC, camd approved these changes

2020-11-03 08:28 UTC, merged