Bug 1671550 Fix build metrics regression template
mozilla/treeherder pull request #6806
Opened 2020-10-16 06:26 UTC by alexandru-io

Probably the CC'ed person in this template changed their email and it gives an error when submitting new bug.

2020-10-16 08:45 UTC, ionutgoldan requested changes

2020-10-16 08:45 UTC, ionutgoldan commented on treeherder/perf/fixtures/performance_bug_templates.yaml
> +    cc_list: froydnj+bz@gmail.com
I don't think Nathan is working at Mozilla anymore. We should leave the `cc_list` blank instead.

2020-10-23 07:51 UTC, ionutgoldan approved these changes
Looking good now!

2020-10-23 23:45 UTC, camd approved these changes

2020-10-26 07:43 UTC, merged