Bug 1681880 TypeError: e[0] is undefined when hiding all data series
mozilla/treeherder pull request #6910
Opened 2020-12-11 08:33 UTC by alexandru-io

This bug was introduced when the improvement of showing the graph timeline up to current date instead of up to the date of last datapoint.
![Screenshot from 2020-12-11 10-25-22](https://user-images.githubusercontent.com/47977085/101880503-b1916e80-3b9b-11eb-8868-e683a87c22b8.png)

### Before
- by clicking to hide the series in the graph is shown `TypeError: e[0] is undefined`
![Screenshot from 2020-12-11 10-25-56](https://user-images.githubusercontent.com/47977085/101880675-f87f6400-3b9b-11eb-93ec-3e6df4286133.png)

### After

- [x] by clicking to hide the series in the graph is shown an empty graph
![Screenshot from 2020-12-11 10-26-31](https://user-images.githubusercontent.com/47977085/101880718-0b923400-3b9c-11eb-8cb1-232f40e82460.png)

2020-12-15 00:43 UTC, camd approved these changes

2020-12-17 14:34 UTC, alexandru-io commented
@ionutgoldan can I have this merged and deployed, please?

2020-12-18 13:42 UTC, ionutgoldan requested changes
This ensures the page doesn't break anymore. But I don't think it's the correct fix.

I don't see why the X & Y axis should update if there's no visible data. They should simply remain the same.

I think we need to look for another solution.

2020-12-18 14:02 UTC, ionutgoldan commented
I think we shouldn't update the `zoomDomain` when we don't have any visible data. We could guard against that inside the `updateGraphs()` method [here](https://github.com/mozilla/treeherder/blob/10882d38b82651220e96877030f14f9eb1d2e9a1/ui/perfherder/graphs/GraphsContainer.jsx#L172).

2021-01-06 07:51 UTC, ionutgoldan approved these changes

2021-01-06 07:52 UTC, merged