Bug 1679019 - Selecting the checkbox for an alert summary in perfherder should check only the untriaged alerts
mozilla/treeherder pull request #6940
Opened 2021-01-04 14:10 UTC by esanuandra

2021-01-04 14:17 UTC, esanuandra commented
![image](https://user-images.githubusercontent.com/63001299/103544169-56a41c00-4ea8-11eb-9a12-0c47ce0a7cc2.png)

2021-01-11 14:53 UTC, esanuandra commented
Updated version 
![image](https://user-images.githubusercontent.com/63001299/104197295-7f3e8f80-542d-11eb-95e9-4ee9cec56ec9.png)

2021-01-12 13:07 UTC, ionutgoldan requested changes
~~We should disable the dropdown if the user isn't logged in.~~
Oh, I just noticed this is disabled. Nevermind....

![dropdown-shouldnt-be-visible-if-logout](https://user-images.githubusercontent.com/12194756/104317991-727e7200-54e7-11eb-867a-799a50c2ee68.PNG)

2021-01-12 13:47 UTC, ionutgoldan commented
We should provide test coverage for this aspect as well.

2021-01-12 14:13 UTC, ionutgoldan requested changes

2021-01-12 14:13 UTC, ionutgoldan commented on ui/perfherder/alerts/AlertTable.jsx
> +    if (selectedStatus === status.all) {
Could we do an if/else if chain? It's easier to assert the code's implications this way.
(For example, if the status is none, we'd hit the 1st branch & the 3rd one.)

2021-01-12 14:19 UTC, ionutgoldan requested changes

2021-01-12 14:19 UTC, ionutgoldan commented on ui/perfherder/alerts/AlertTable.jsx
> +                        toggleAllAlerts={() => {
Couldn't we remove this small helper function? We seem to already do the same thing via `selectAlertByStatus(all)`.

2021-01-12 14:21 UTC, ionutgoldan commented
Also, please elaborate a test coverage plan (just leave a comment in this PR).
After that, you can start implementing the test coverage.

2021-01-13 09:03 UTC, esanuandra commented
> ~We should disable the dropdown if the user isn't logged in.~
> Oh, I just noticed this is disabled. Nevermind....
> 
> ![dropdown-shouldnt-be-visible-if-logout](https://user-images.githubusercontent.com/12194756/104317991-727e7200-54e7-11eb-867a-799a50c2ee68.PNG)

I believe it is better if we disable the toggle and make it have a similar behavior like the left checkbox
![image](https://user-images.githubusercontent.com/63001299/104429898-c5f7cb00-558e-11eb-93c2-425bbbcc00d3.png)

2021-01-14 07:52 UTC, esanuandra commented
### Tests:

1. user is not logged in -> check alerts dropdown toggle is disabled
2. user is logged in -> check alerts dropdown toggle is enabled
3. user is logged in & clicks on check alerts dropdown toggle -> check alerts dropdown is shown with the 4 options ('All', 'None', 'Triaged', 'Untriaged')
4. user is logged in & checks 'All' option from check alerts dropdown -> all visible alerts are checked
5. user is logged in & checks 'None' option from check alerts dropdown -> no alert is being checked or alerts are unchecked if they were checked before
6. user is logged in & checks 'Triaged' option from check alerts dropdown -> all the alerts that are visible and not untriaged are checked
7. user is logged in & checks 'Untriaged' option from check alerts dropdown -> all the alerts that are visible and untriaged are checked
8. user is logged in & double clicks on 'All' option from check alerts dropdown -> all visible alerts are (remain) checked, the button does not act as a toggle, it does not unchecks alerts

2021-01-14 09:21 UTC, ionutgoldan requested changes

2021-01-14 09:21 UTC, ionutgoldan commented on ui/perfherder/alerts/SelectAlertsDropdown.jsx
> +            aria-labelledby={`alert summary ${alertSummary.id.toString()} title`}
What's the purpose of this `aria-labelledby`? I feel like it's not used properly.

2021-01-14 09:21 UTC, ionutgoldan commented on ui/perfherder/alerts/SelectAlertsDropdown.jsx
> +            data-testid={`alert summary ${alertSummary.id.toString()} checkbox`}
I prefer we don't use `data-testid` on the frontend just to enhance our testing abilities.
react testing library has lots of ways of identifying test components. For example, by selecting them based on ARIA attributes.

2021-01-14 09:21 UTC, ionutgoldan commented on ui/perfherder/alerts/AlertTable.jsx
> +                        alertSummary={alertSummary}
I don't think this parameter is that useful.

2021-01-14 09:21 UTC, ionutgoldan commented on ui/perfherder/alerts/AlertTable.jsx
> +  selectAlertsByStatus = (selectedStatus) => {
This logic feels more like the responsibility of `SelectAlertsDropdown`. Wouldn't it be better to try to move it there?
All the parent needs to know is what alerts have been selected by the dropdown & whether all have been selected or not.

2021-01-14 09:24 UTC, ionutgoldan commented
> 
> ### Tests:
> 
>     1. user is not logged in -> check alerts dropdown toggle is disabled
> 
>     2. user is logged in -> check alerts dropdown toggle is enabled
> 
>     3. user is logged in & clicks on check alerts dropdown toggle -> check alerts dropdown is shown with the 4 options ('All', 'None', 'Triaged', 'Untriaged')

This is redundant, as it is included in the 4 tests bellow.

>     4. user is logged in & checks 'All' option from check alerts dropdown -> all visible alerts are checked
> 
>     5. user is logged in & checks 'None' option from check alerts dropdown -> no alert is being checked or alerts are unchecked if they were checked before
> 
>     6. user is logged in & checks 'Triaged' option from check alerts dropdown -> all the alerts that are visible and not untriaged are checked
> 
>     7. user is logged in & checks 'Untriaged' option from check alerts dropdown -> all the alerts that are visible and untriaged are checked
> 
>     8. user is logged in & double clicks on 'All' option from check alerts dropdown -> all visible alerts are (remain) checked, the button does not act as a toggle, it does not unchecks alerts

I don't think this is needed.

2021-01-15 14:43 UTC, ionutgoldan commented on ui/perfherder/alerts/SelectAlertsDropdown.jsx
> +            data-testid={`alert summary ${alertSummary.id.toString()} checkbox`}
Seems like without this, we'd break some of our existing tests. I'm cancelling this request.

2021-01-15 16:24 UTC, ionutgoldan requested changes

2021-01-15 16:24 UTC, ionutgoldan commented on ui/perfherder/alerts/SelectAlertsDropdown.jsx
> +            aria-label="select-alerts-dropdown-toggle-label"
The string here should look like natural language. Also, we should make it shorter. Maybe "Alert selection options"?

2021-01-15 16:24 UTC, ionutgoldan commented on tests/ui/perfherder/alerts-view/select_alerts_dropdown_test.jsx
> +  expect(dropdownToggle).toHaveClass('disabled');
There's a better suited test API for this: `toBeDisabled()`.

2021-01-15 16:24 UTC, ionutgoldan commented on tests/ui/perfherder/alerts-view/select_alerts_dropdown_test.jsx
> +  expect(dropdownToggle.classList.contains('disabled')).toBe(false);
Again, there's a better API for this: `toBeEnabled()`.

2021-01-15 16:24 UTC, ionutgoldan commented on tests/ui/perfherder/alerts-view/select_alerts_dropdown_test.jsx
> +test("Selecting 'All' option from dropdown checks all the visibile alerts", async () => {
Typo on "visibile".

2021-01-15 16:24 UTC, ionutgoldan commented on tests/ui/perfherder/alerts-view/select_alerts_dropdown_test.jsx
> +const testAlertSummary = testAlertSummaries[0];
This summary only has untriaged alerts. We should make sure we have multiple alerts with multiple statuses. I think `untriaged`, `invalid` & `acknowledged` would suffice.

2021-01-18 15:13 UTC, ionutgoldan approved these changes
Looks good!

2021-01-18 15:16 UTC, merged