Bug 1689066 - Bad representation for deleted signatures in email notification
mozilla/treeherder pull request #6997
Opened 2021-01-27 14:37 UTC by beatrice-acasandrei

2021-01-28 09:47 UTC, ionutgoldan commented on treeherder/model/data_cycling/signature_remover.py
>          properties = []
Could you add the type annotation for this method' s parameter?

2021-01-28 09:47 UTC, ionutgoldan commented on treeherder/model/data_cycling/signature_remover.py
> +                "repository": signature.repository.name,
Could we add a test for the email' s content? So we don't have to send a real email to check this works as expected.

2021-02-04 11:07 UTC, ionutgoldan requested changes
Please also rebase on latest master.

2021-02-04 11:07 UTC, ionutgoldan commented on treeherder/model/data_cycling/email_service.py
> +    def content(self):
Let's provide test coverage for the content itself.

2021-02-04 11:07 UTC, ionutgoldan commented on tests/model/cycle_data/test_perfherder_cycling.py
> +def test_email_payload(test_perf_signature):
This feels like we're testing a private method, which isn't good practice.

2021-02-05 09:23 UTC, ionutgoldan approved these changes
Looking good!

2021-02-05 23:25 UTC, sarah-clements approved these changes

2021-02-08 08:23 UTC, merged