Bug 1689103 - Don't notify removal of try signatures
mozilla/treeherder pull request #7000
Opened 2021-01-29 12:55 UTC by beatrice-acasandrei

2021-01-29 14:03 UTC, ionutgoldan requested changes

2021-01-29 14:03 UTC, ionutgoldan commented on treeherder/model/data_cycling/signature_remover.py
> +                if perf_signature.repository.name == 'try':
This is still conditioned by our email thresholds.
As a result, the execution flow isn't deterministic.

2021-02-01 08:03 UTC, ionutgoldan reviewed
Please also provide the appropriate test coverage.

2021-02-01 08:03 UTC, ionutgoldan commented on treeherder/model/data_cycling/signature_remover.py
> +        self._remove_try_signatures(signatures)
Let's highlight we're only deleting empty try signatures here.

2021-02-03 15:08 UTC, airimovici reviewed
After https://github.com/mozilla/treeherder/pull/7008 fix got merged, the tests should pass after a force restart (an empty push)

2021-02-04 08:12 UTC, airimovici approved these changes
Test passes, all empty try signatures are removed. It would be more solid if we also test with at least one try signature that has data and assert that it doesn't get removed

2021-02-04 10:17 UTC, ionutgoldan reviewed
I agree with Alex.

2021-02-04 10:17 UTC, ionutgoldan approved these changes

2021-02-05 23:23 UTC, sarah-clements approved these changes

2021-02-09 08:29 UTC, ionutgoldan requested changes

2021-02-09 08:29 UTC, ionutgoldan commented on tests/model/cycle_data/test_perfherder_cycling.py
> +    signature_without_perf_data = PerformanceSignature.objects.create(
I don't think we need to include signatures without data.

2021-02-09 09:08 UTC, ionutgoldan approved these changes

2021-02-09 09:09 UTC, merged