Bug 1694107 - Time range dropdown not synced with Graphs view
mozilla/treeherder pull request #7027
Opened 2021-02-23 12:25 UTC by beatrice-acasandrei

2021-02-23 15:12 UTC, ionutgoldan requested changes
There's still a bug in our logic.

#### Steps to reproduce

1. Go to default page of Graphs view.
2. Click on **Add test data**.
3. Select **Last 60 days**.
4. Click the **X** button to close the modal.
5. Click again on **Add test data**.

Expected:
Time range from modal resets to the default value.

What we got instead:
Time range keeps its new value.

2021-02-23 15:12 UTC, ionutgoldan commented on ui/perfherder/graphs/TestDataModal.jsx
> +      this.setState({ innerTimeRange: this.props.timeRange });
We could simply use `timeRange`.

2021-02-24 09:24 UTC, ionutgoldan commented on ui/perfherder/graphs/TestDataModal.jsx
> +    this.setState({ innerTimeRange: this.props.timeRange });
We already have a `setState()` call. We could simply make use of it.

2021-02-24 12:39 UTC, ionutgoldan requested changes

2021-02-24 12:39 UTC, ionutgoldan commented on ui/perfherder/graphs/TestDataModal.jsx
>        },
I was actually referring to adding an entry here, in this existing `setState()`.

2021-02-24 14:56 UTC, airimovici approved these changes

2021-02-24 14:59 UTC, ionutgoldan approved these changes

2021-02-24 15:00 UTC, merged