WIP Bug 1690259 - Keep historical data
mozilla/treeherder pull request #7040
Opened 2021-03-05 14:45 UTC by beatrice-acasandrei

2021-03-09 07:42 UTC, ionutgoldan commented on treeherder/perf/models.py
> +    def has_data_with_historical_value(self):
This starts to look like a big method & isn't easy to follow. Let's try & keep it under 10 lines of code.

2021-03-11 07:51 UTC, ionutgoldan requested changes

2021-03-11 07:51 UTC, ionutgoldan commented on treeherder/perf/models.py
> +            if data_was_kept_for_one_year(most_recent_perf_data):
We don't need this check. There's a separate strategy that removes data older than one year.

2021-03-11 07:51 UTC, ionutgoldan commented on treeherder/perf/models.py
> +def has_one_month_worth_of_data(perf_data):
These helper functions should be used as private/protected methods inside the main class.

2021-03-15 15:11 UTC, airimovici commented on treeherder/perf/models.py
> +    def _has_one_month_worth_of_data(perf_data):
maybe rename this to `_has_enough_data`

2021-03-22 13:16 UTC, ionutgoldan commented on treeherder/perf/models.py
> +            (end_date.year - start_date.year) * 12 + (end_date.month - start_date.month) + 1
Why have we incremented this by one?

2021-03-22 13:33 UTC, ionutgoldan requested changes

2021-03-22 13:33 UTC, ionutgoldan commented on tests/model/cycle_data/test_perfherder_cycling.py
> +    test_perf_signature.last_updated = four_months_ago_timestamp
I see we prepare this same signature in all 3 tests. We could consider DRYing it.

2021-03-22 13:34 UTC, ionutgoldan requested changes

2021-03-22 13:34 UTC, ionutgoldan commented on tests/model/cycle_data/test_perfherder_cycling.py
> +    for data_point in perf_data:
This assert should be optimized, to run faster.

2021-03-24 07:52 UTC, ionutgoldan commented on tests/conftest.py
> +def test_perf_signature_3(test_perf_signature):
Could you give this fixture a more meaningful name? The "3" suffix is totally opaque.

2021-03-24 07:52 UTC, ionutgoldan commented on tests/model/cycle_data/test_perfherder_cycling.py
> +    assert perf_signature in PerformanceSignature.objects.all()
I still think we could optimize these asserts.

2021-03-24 07:52 UTC, ionutgoldan commented on treeherder/perf/models.py
> +            if len(perf_data) >= 2 and self._has_enough_data_points(perf_data):
I think we can move this `len()` check directly in the protected method.

2021-03-25 08:47 UTC, ionutgoldan requested changes
I forgot to tell you: we also need to update the online docs [here](https://treeherder.readthedocs.io/data_cycling.html), to reflect the changes.

2021-03-25 12:00 UTC, ionutgoldan approved these changes

2021-03-25 12:50 UTC, merged