Bug 1698548 - Link to Talos test documentation
mozilla/treeherder pull request #7073
Opened 2021-03-29 12:13 UTC by beatrice-acasandrei

2021-04-02 12:33 UTC, ionutgoldan requested changes
I also noticed the following error when clicking on a subtests hyperlink from Compare view:

```javascript
Something went wrong TypeError: dropdownOptions[0] is undefined
```

2021-04-02 12:33 UTC, ionutgoldan commented on ui/perfherder/graphs/LegendCard.jsx
> +          {framework === 'talos' && <a href={getTalosDocsURL(suite)}>(docs)</a>}
It'd be more consistent to provide the link right after the series name (immediately above).

2021-04-02 12:33 UTC, ionutgoldan commented on ui/perfherder/compare/CompareTable.jsx
> +                {framework === 'talos' && <a href={url}> (docs)</a>}
Could you look for a way to display the `(docs)` link with blue, like normal anchor links look like?

2021-04-06 11:58 UTC, airimovici commented on ui/perfherder/compare/CompareTable.jsx
> +                    {' '}
This space can be moved outside outside the `<a>`. Just before it, so we avoid having the space underlined on hover

2021-04-06 12:42 UTC, airimovici requested changes

2021-04-06 12:42 UTC, airimovici commented on ui/perfherder/compare/CompareTable.jsx
> +                  <a href={url} style={{ color: '#23527c' }}>
we should have the style defined in `perf.css` file.

https://github.com/mozilla/treeherder/blob/master/ui/css/perf.css#L312

```
.compare-table .result-links a,
.compare-table .subtest-header a {
  color: #23527c;
}
```

2021-04-07 14:07 UTC, airimovici approved these changes

2021-04-08 06:12 UTC, ionutgoldan commented
I found a weird bug.

### Steps to reproduce

1. Go to Alerts view.
2. Select a random alert summary.
3. Add some random notes to it.
4. Click on the summary' s header link.

#### Expected results
User gets redirected to that single summary.

#### Actual results
Following Javascript error is dumped in the UI:

```javascript
Something went wrong TypeError: alert.title is undefined
```

2021-04-08 06:13 UTC, ionutgoldan requested changes
We need to fix the reported bug & do more thorough manual tests.

2021-04-16 10:02 UTC, closed without merging