Bug 1724866 - Remove 'Hide improvements' button from Alerts View
mozilla/treeherder pull request #7236
Opened 2021-08-11 07:30 UTC by sorintoma

2021-08-11 12:35 UTC, esanuandra requested changes

2021-08-11 12:35 UTC, esanuandra commented on tests/ui/perfherder/alerts-view/alerts_test.jsx
>    expect(alert2).toBeInTheDocument();
These need to be removed as well.

2021-08-11 12:35 UTC, esanuandra commented on tests/ui/perfherder/alerts-view/alerts_test.jsx
> -  expect(alertSummary1).not.toBeInTheDocument();
We should change this from `.not.toBeInTheDocument()` to  `.toBeInTheDocument()` since the previous filter is not applied anymore.

2021-08-11 14:37 UTC, esanuandra approved these changes
Looks good!

2021-08-12 07:19 UTC, beatrice-acasandrei approved these changes

2021-08-12 07:24 UTC, merged