Bug 1725334 - Graphs View - Page does not reset when clicking header fixed
mozilla/treeherder pull request #7259
Opened 2021-09-02 08:34 UTC by sorintoma

2021-09-03 08:13 UTC, beatrice-acasandrei approved these changes

2021-09-06 11:05 UTC, airimovici commented on ui/perfherder/graphs/GraphsView.jsx
> +      this.resetPageOnHeaderClick();
We don't need to hide the setstate, we should use it directly and suppress the lint warning

```
    {
      // eslint-disable-next-line react/no-did-update-set-state
      this.setState({
        testData: [],
      });
    }
```

2021-09-06 11:09 UTC, esanuandra requested changes

2021-09-06 11:09 UTC, esanuandra commented on ui/perfherder/graphs/GraphsView.jsx
> +      this.props.location.search !== prevProps.location.search
We can use destructors for the information we need from props and state.

2021-09-07 15:04 UTC, esanuandra approved these changes

2021-09-08 11:48 UTC, merged