Bug 1744530 - Add user feedback on click for the copy to clipboard button
mozilla/treeherder pull request #7337
Opened 2021-12-06 15:03 UTC by sorintoma

2021-12-07 12:56 UTC, esanuandra requested changes

2021-12-07 12:56 UTC, esanuandra commented on ui/shared/Clipboard.jsx
> +  const [copied, setCopied] = useState(false);
I see that we are using `hooks` here. At the moment they are not used anywhere else in the project. We should discuss with the team if it is suitable to integrate them in the future.
To use `state` we should change from `functional component` to `class component`.

2021-12-08 13:27 UTC, beatrice-acasandrei approved these changes

2021-12-09 13:13 UTC, esanuandra approved these changes

2021-12-09 13:45 UTC, merged