Update Django from 3.2 to 4.0
mozilla/treeherder pull request #7479
Opened 2022-07-06 14:06 UTC by vrigal

2022-07-08 13:44 UTC, vrigal commented
Tests are not ran in the CI because of a deprecation warning from dockerflow dependency (ref. https://github.com/mozilla-services/python-dockerflow/issues/66).

Otherwise, there are 1 error and 2 fails. It should be possible to add a tearDown method as the failing tests run fine when executes separately.
```
E               Traceback (most recent call last):
E                 File "/usr/local/lib/python3.9/site-packages/celery/utils/collections.py", line 250, in __getitem__
E                   return mapping[_key]
E               ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.26.0.5', 41964), raddr=('172.26.0.3', 5672)>
```

2022-07-11 22:20 UTC, jmaher commented
@vrigal are you aware of anything we can do to fix the deprecated tools/packages/scripts in dockerflow?

2022-07-13 09:57 UTC, Archaeopteryx commented
The python-dockerflow fix landed: https://github.com/mozilla-services/python-dockerflow/commit/0f640cc031aecf5d61432fc141719e5603d66acf

2022-07-15 22:12 UTC, jmaher commented
look in dev.in and consider upgrading `django-debug-toolbar` and maybe others.

2022-07-18 11:45 UTC, vrigal commented
I could update dev dependencies, but there is the same deprecation warning (`RemovedInDjango41Warning`) with the latest version of django-extensions. We could eventually separate development and tests related dependencies.

A more concerning issue another deprecation warning raised by `pytest-freezegun`, which is mentioned here :
* https://github.com/mozilla/treeherder/pull/7445#issue-1235147252]
* https://github.com/spulec/freezegun/issues/435

We could eventually run pytest with `-W ignore::DeprecationWarning`, or remove this dependency and skip a certain amount of tests

2022-07-18 11:49 UTC, vrigal commented
In fact we can probably wait https://github.com/ktosiek/pytest-freezegun/pull/38 to be merged

2022-07-18 15:20 UTC, La0 requested changes

2022-07-18 15:20 UTC, La0 commented on treeherder/config/settings.py
> +USE__TZ = False
I guess it should be `USE_TZ`, single underscore

2022-07-18 16:34 UTC, jmaher reviewed
the changes in general look good- curious why the line numbers on the test data had to change?

2022-07-21 15:46 UTC, vrigal commented
> the changes in general look good- curious why the line numbers on the test data had to change?

Line numbers change in tests is related to the update of the responses package (works with `0.14.0` and fails with `0.15.0`).
It should not alter treeherder in my opinion, as it is a tests-related package.

2022-07-21 15:51 UTC, jmaher commented
asking @La0 for review as there are pending requested/resolved changes.

2022-07-25 12:17 UTC, jmaher approved these changes

2022-07-26 15:58 UTC, merged