Bug 1836153 - Changed line 114 in compare_tasks.py
mozilla/treeherder pull request #7710
Opened 2023-06-01 01:23 UTC by tfdeleon

Bug-1836153 - Changed python version from 3.9 -> 3. Changed line 114 in compare_tasks.py from 'th_instancely' to "instance"

2023-06-06 17:40 UTC, jmaher commented on .pre-commit-config.yaml
> +        language_version: python3
we shouldn't change this, the more specific we can get the better- if there is a reason to change it, let me know

2023-06-07 12:50 UTC, jmaher requested changes
please address the comment about python 3.9 vs python 3

2023-06-10 01:12 UTC, tfdeleon commented
﻿﻿Hey Joel, I hope your trip went well ! Sorry about resubmitting without changing anything. We've been in our project week for our bootcamp and I was just trying to see what you were referring to in the bug and I accidentally clicked "Edit bug" thinking it'll show me what I did wrong. But I accidentally submitted. I just finished submitting my project and it went well! Learned so much from this experience. I will get those bugs fixed this weekend. -TimOn Jun 7, 2023, at 8:51 AM, Joel Maher ***@***.***> wrote:﻿
@jmaher requested changes on this pull request.

please address the comment about python 3.9 vs python 3

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-06-15 01:15 UTC, jmaher commented
all is fixed :)

2023-06-15 01:24 UTC, merged