Add steps for local data ingestion in docs
mozilla/treeherder pull request #7790
Opened 2023-09-01 21:16 UTC by sumairq

## This PR updates the docs on steps to ingest data locally.

It is a solution for https://bugzilla.mozilla.org/show_bug.cgi?id=1850748

- It includes steps to help contributors set up a local data ingestion environment.

2023-09-01 22:08 UTC, gmierz requested changes
Nice work @sumairq :) just a few additional things we'll need to add to make it clearer for others.

2023-09-01 22:08 UTC, gmierz commented on docs/pulseload.md
> +**Here is an example flow you can use:**
We can remove this line

2023-09-01 22:08 UTC, gmierz commented on docs/pulseload.md
> +## Setup
Change this to `## Setup for Perfherder Development`

2023-09-01 22:08 UTC, gmierz commented on docs/pulseload.md
> +(These steps should help you set up everything you need to ingest data locally while working on perfherder)
We could remove the parentheses for this line

2023-09-01 22:08 UTC, gmierz commented on docs/pulseload.md
> +You can use **dbeaver-ce**
I recommend only mentioning that you can use any database viewer of your choice here. You could mention `dbeaver-ce` in parentheses like `(e.g. dbeaver-ce, mysql workbench, etc.)`

2023-09-01 22:08 UTC, gmierz commented on docs/pulseload.md
> +##### Run the following in separate window while running above to do ingestion
Below this, we should add a comment saying that these commands actually perform the fetches for the data, and that they are run sequentially in the same window. The first command makes the second one run faster. Also, we should mention here the `--enable-eager-celery` triggers the log parsing which is required to capture the `PERFHERDER_DATA` output.

2023-09-01 22:27 UTC, Archaeopteryx reviewed
Thank you for extending the documentation.

2023-09-01 22:27 UTC, Archaeopteryx commented on docs/pulseload.md
> +**For ingesting multple pushes:**
Typo.

2023-09-01 22:27 UTC, Archaeopteryx commented on docs/pulseload.md
> +```bash
There should be a warning this can take a long time to ingest and parse everything.

2023-09-01 22:27 UTC, Archaeopteryx commented on docs/pulseload.md
> +docker-compose up --build
`--build` has been already used above and should not be needed here.

2023-09-01 22:27 UTC, Archaeopteryx commented on docs/pulseload.md
> +if it was already ingested by another user Unfortunately, **Pulse** doesn't support creating
This needs a full stop between the two sentences.

2023-09-02 10:31 UTC, gmierz commented
@sumairq looking at the other documentation we have, and I'm wondering if it would make more sense to have this information on this page (maybe in the ingesting pushes section): https://treeherder.readthedocs.io/installation.html

What do you think?

2023-09-04 14:45 UTC, Archaeopteryx approved these changes
Thank you.

2023-09-27 19:12 UTC, gmierz commented
> a link to the detailed setup in the `Loading pulse data` section?

I'm not sure about this, why do you think the `Loading pulse data` section would be better? While navigating locally, I found that it's a bit harder to find it here versus the installation page.

2023-10-04 14:12 UTC, gmierz commented
@sumairq would you be able to fix up this PR to only show the files modified by your PR? It looks like there are merge conflicts as well that need to be resolved. I think a forced push from an up-to-date branch could help.

2026-05-06 14:52 UTC, beatrice-acasandrei commented
Due to the recent inactivity we can close this PR, this issue will be wrapped up in https://github.com/mozilla/treeherder/pull/9477.

2026-05-06 14:52 UTC, closed without merging