Bug 1850785 - Allow for Marionette failures to be filed as single tra…
mozilla/treeherder pull request #7803
Opened 2023-09-13 22:12 UTC by jmaher

…cking bugs. r=aryx

2023-09-14 16:01 UTC, Archaeopteryx requested changes

2023-09-14 16:25 UTC, jmaher commented
thanks for the drive by; this patch is probably 50% complete, I hope to have it done this week and will request a review when it is ready.  I will support Marionette as well as some talos errors

2023-09-14 17:23 UTC, jmaher commented on treeherder/model/error_summary.py
> +            test_name_or_path = "%s.py" % test_name_or_path.split(".py ")[0]
I need to revisit this logic, thanks for pointing out the need to check if .py exists.  Ideally I can find a way to determine if this is marionette based on other path or test line specifics.

2023-09-14 23:37 UTC, jmaher commented
these changes will allow for bugfiler to work properly for talos crashes and marionette regular failures.

In addition there are some changes to the bug suggestions (backend) which will find a marionette test line and strip it to match the test path, not the full failure path.

2023-09-21 23:12 UTC, Archaeopteryx commented
This landed with #7810. Can you close it?

2023-09-22 00:24 UTC, closed without merging