Bug 1823654 - Switch to Ruff for linting
mozilla/treeherder pull request #7898
Opened 2024-01-23 15:49 UTC by yschneider-sinneria

I replaced the flake8 pre-commit hook with ruff's and migrated the configuration found in:
- [setup.cfg](https://github.com/mozilla/treeherder/blob/e91eb1cd66c13ee592da45185c718276433e4976/setup.cfg#L1-L8)
- [tox.ini](https://github.com/mozilla/treeherder/blob/e91eb1cd66c13ee592da45185c718276433e4976/tox.ini#L58-L59)
To Ruff's configuration in `pyproject.toml`.

I kept the default Flake8 rules, `pyflakes` (`"F"` rule) and `pycodestyle` (`"E"` and `"W"` rules).

2024-01-23 15:52 UTC, yschneider-sinneria commented on pyproject.toml
> +"treeherder/perf/sheriffing_criteria/criteria_tracking.py" = ["E714"]
Ruff suggests

```diff
--- a/treeherder/perf/sheriffing_criteria/criteria_tracking.py
+++ b/treeherder/perf/sheriffing_criteria/criteria_tracking.py
@@ -128,9 +128,9 @@ class ConcurrencyStrategy:
 
         if not issubclass(self._pool_class, Pool):
             raise TypeError(f'Expected Pool (sub)class parameter. Got {self._pool_class} instead')
-        if not type(thread_wait) is timedelta:
+        if type(thread_wait) is not timedelta:
             raise TypeError('Expected timedelta parameter.')
-        if not type(check_interval) is timedelta:
+        if type(check_interval) is not timedelta:
             raise TypeError('Expected timedelta parameter.')
```

2024-01-23 15:52 UTC, yschneider-sinneria commented on pyproject.toml
> +"treeherder/push_health/utils.py" = ["E713"]
Ruff suggests
```diff
--- a/treeherder/push_health/utils.py
+++ b/treeherder/push_health/utils.py
@@ -64,7 +64,7 @@ def clean_test(test, signature, message):
 
     if '|' in clean_name:
         parts = clean_name.split('|')
-        clean_parts = filter(lambda x: not x.strip() in trim_parts, parts)
+        clean_parts = filter(lambda x: x.strip() not in trim_parts, parts)
         clean_name = '|'.join(clean_parts)
```

2024-01-23 15:54 UTC, yschneider-sinneria commented on pyproject.toml
> +  "E231",
These rules are not triggered right now so I'm not sure it's still relevant to ignore them.

2024-01-23 16:00 UTC, La0 requested changes
Overall a great first gentle integration of ruff.

Here is the [first run on CI](https://app.circleci.com/pipelines/github/mozilla/treeherder/5735/workflows/7e5a7a79-3649-4c09-8ed0-dc3f6c31c5ab/jobs/23999/parallel-runs/0/steps/0-107) :+1:

2024-01-23 16:06 UTC, yschneider-sinneria commented on pyproject.toml
> +  "E231",
Done in https://github.com/mozilla/treeherder/pull/7898/commits/5146fb4adbb4ba79d9f571d2eec6fea196978493

2024-01-23 16:06 UTC, yschneider-sinneria commented on pyproject.toml
> +"treeherder/perf/sheriffing_criteria/criteria_tracking.py" = ["E714"]
Done in https://github.com/mozilla/treeherder/pull/7898/commits/bdcbae98e269b20edd3d0e0732bd53011aec04ac

2024-01-23 16:22 UTC, La0 approved these changes

2024-01-23 17:04 UTC, marco-c commented
Should we disable black too and rely on ruff for formatting too?

2024-01-24 12:01 UTC, La0 commented
Overall a 

> Should we disable black too and rely on ruff for formatting too?

Yes but that would be another PR, as there may be some extra formatting changes introduced

2024-01-24 12:14 UTC, Archaeopteryx approved these changes

2024-01-24 12:15 UTC, Archaeopteryx commented
Thank you for the patch.

2024-01-24 12:15 UTC, merged